### ISSUE TITLE
Remove Iris

### ISSUE THREAD

**Issue by yashsriv** [pclubiitk/student-search#1]
Instead of Iris for http routing, try and find an alternative which works better.

**Comment by sakshamsharma** [comment]
@pallavagarwal07 can comment on how gorilla is. I'd recommend a framework, but it really doesn't matter for such a small app :smile: Choose any you want, or perhaps just go cowboy with bare `net/http` or `fasthttp`

**Comment by yashsriv** [comment]
Replaced Iris with Echo since [Iris Has Been Acquired](https://github.com/kataras/iris#iris-has-been-acquired)
