### ISSUE TITLE
Search is slow [ui]

### ISSUE THREAD

**Issue by milindl** [pclubiitk/student-search#11]
Some timing results against the old student search, and how we compare. Used Chrome Profiler on my PC.

Test: 
1. Go to student search page.
2. Select "Year" and choose "Y15".

This is what the profiles show:
**Our search:**
**net time:** ~1420ms (from mouseup to a useable thing with list of students clearly visible)
**call to filter():** ~15ms (noting this because initially I thought filtering entries would be the cause of jank but apparently no)

it should be noted that this one big event handler for onclick is run for a **_~830ms._** The point here is that the handler is run on the main thread of the browser, so it causes a visible slowness (jank) in the UI.
This I think is the cause of the whole UI freezing up a bit when mouseup is triggerd on "Y15".

**Old Student Search:**
**Net time:** ~520ms
The mouseup event handler used causes a delay of ~50ms only on the main thread (which leads to the UI looking much "snappier")

I don't have any idea how to fix this, would appreciate any views.
PS: Attached profiles! [load in chrome profiler]
[profiles.zip](https://github.com/pclubiitk/student-search/files/1142198/profiles.zip)

**Comment by yashsriv** [comment]
@milindl Can you please test [this branch](https://github.com/yashsriv/student-search-1/tree/improve/speed) on your pc as I can't measure these changes on my laptop (its too fast).

**Comment by milindl** [comment]
Okay, new stats show a definite improvement in the Main thread, the handler takes around **420ms**.
Net time takenis **930ms** . Better, but not as good as the old search by a long shot.

**Comment by yashsriv** [comment]
Fixed in #16
